# Generated by Django 4.1 on 2022-08-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_item', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_item', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50, unique=True)),
                ('recipe', models.TextField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(to='mealprep.ingredient')),
            ],
            options={
                'verbose_name': 'Meal',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealprep.mealitem')),
            ],
            options={
                'verbose_name_plural': 'Meal Plan',
            },
        ),
    ]
